export const gameTiles = [
  ['','','','','','','','','','','','','','','','','','','',''],
  ['','','','','','','','','','','','','','','','','','','',''],
  ['','','','','','','','','','','','','','','','','','','',''],
  ['','','','','','','','','','','','','','','','','','','',''],
  ['','','','','','','','','','','','','','','','','','','',''],
  ['','','','','','','','','','','','','','','','','','','',''],
  ['','','','','','','','','','','','','','','','','','','',''],
  ['','','','','','','','','','','','','','','','','','','',''],
  ['','','','','','','','','','','','','','','','','','','',''],
  ['','','','','','','','','','','','','','','','','','','',''],
  ['','','','','','','','','','','','','','','','','','','',''],
  ['','','','','','','','','','','','','','','','','','','',''],
  ['','','','','','','','','','','','','','','','','','','',''],
  ['','','','','','','','','','','','','','','','','','','',''],
  ['','','','','','','','','','','','','','','','','','','',''],
  ['','','','','','','','','','','','','','','','','','','',''],
  ['','','','','','','','','','','','','','','','','','','',''],
  ['','','','','','','','','','','','','','','','','','','',''],
  ['','','','','','','','','','','','','','','','','','','',''],
  ['','','','','','','','','','','','','','','','','','','','']
  
]
export const visited =[ 
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,],
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,],
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,],
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,],
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,],    
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,],
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,],
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,],
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,],
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,],
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,],
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,],
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,],
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,],
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,],
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,],
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,],
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,],
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,], 
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,] ]
export const path = [ 
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,],
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,],
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,],
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,],
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,],    
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,],
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,],
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,],
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,],
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,],
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,],
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,],
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,],
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,],
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,],
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,],
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,],
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,],
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,], 
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,] ]
export const maze1 = [['start', '', '', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red'],
 ['red', 'red', '', '', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', '', '', '', '', 'red', 'red'],
 ['red', 'red', 'red', '', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', '', 'red', 'red', '', 'red', 'red'],
 ['red', 'red', 'red', '', '', '', '', '', '', '', '', '', '', '', '', 'red', 'red', '', 'red', 'red'],
 ['red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', '', 'red', 'red'],
 ['red', '', '', '', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', '', '', '', '', 'red', '', 'red', 'red'],
 ['red', '', 'red', '', '', '', '', '', '', '', '', '', '', 'red', 'red', 'red', 'red', '', 'red', 'red'],
 ['red', '', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', '', '', '', '', 'red', '', 'red', 'red'],
 ['red', '', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', '', 'red', 'red'],
 ['red', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'red', 'red'],
 ['red', '', '', '', '', '', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red'],
 ['red', '', 'red', '', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', '', 'red', 'red', 'red', 'red'],
 ['red', '', 'red', '', '', '', '', '', '', '', '', '', '', '', 'red', '', 'red', '', 'red', 'red'],
 ['red', '', 'red', '', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', '', 'red', '', 'red', 'red'],
 ['red', '', 'red', '', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', '', 'red', '', 'red', 'red'],
 ['red', '', 'red', '', 'red', '', '', '', '', '', '', '', '', '', '', '', '', '', 'red', 'red'],
 ['red', '', 'red', '', 'red', 'red', '', 'red', '', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red'],
 ['red', '', '', '', '', '', '', 'red', '', 'red', 'red', 'red', 'red', 'red', 'red', '', 'red', 'red', 'red', 'red'],
 ['red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', '', '', '', '', '', '', 'red', '', 'red', 'red', 'red', 'red'],
 ['red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', '', '', '', '', '', '', 'end']
]
export const logan = [
  ['start', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', 'red', '', '', '', '', 'red', 'red', 'red', 'red', 'red', '', 'red', 'red', 'red', 'red', 'red', '', ''],
  ['', '', 'red', '', '', '', '', 'red', '', '', '', 'red', '', 'red', '', '', '', '', '', ''],
  ['', '', 'red', '', '', '', '', 'red', '', '', '', 'red', '', 'red', '', '', '', '', '', ''],
  ['', '', 'red', '', '', '', '', 'red', '', '', '', 'red', '', 'red', '', 'red', 'red', 'red', '', ''],
  ['', '', 'red', '', '', '', '', 'red', '', '', '', 'red', '', 'red', '', '', '', 'red', '', ''],
  ['', '', 'red', 'red', 'red', 'red', '', 'red', 'red', 'red', 'red', 'red', '', 'red', 'red', 'red', 'red', 'red', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', 'red', 'red', 'red', '', '', 'red', '', '', '', 'red', '', '', '', '', ''],
  ['', '', '', '', 'red', '', '', '', 'red', '', 'red', 'red', '', '', 'red', '', '', '', '', ''],
  ['', '', '', '', 'red', '', '', '', 'red', '', 'red', '', 'red', '', 'red', '', '', '', '', ''],
  ['', '', '', '', 'red', 'red', 'red', 'red', 'red', '', 'red', '', '', 'red', 'red', '', '', '', '', ''],
  ['', '', '', '', 'red', '', '', '', 'red', '', 'red', '', '', '', 'red', '', '', '', '', ''],
  ['', '', '', '', 'red', '', '', '', 'red', '', 'red', '', '', '', 'red', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'end']

]
export const random = [
  ['start', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red'],
  ['', '', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', '', '', '', '', '', '', '', 'red', 'red', 'red'],
  ['red', '', '', '', '', 'red', 'red', '', '', '', '', '', 'red', 'red', 'red', '', '', '', '', 'red'],
  ['red', 'red', '', '', '', '', '', '', '', '', '', 'red', 'red', 'red', 'red', 'red', '', '', '', ''],
  ['red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', ''],
  ['', '', 'red', 'red', 'red', '', '', '', '', '', '', '', '', '', 'red', 'red', 'red', 'red', '', ''],
  ['', '', '', '', '', '', '', 'red', 'red', 'red', 'red', 'red', '', '', '', '', '', '', '', ''],
  ['', 'red', 'red', 'red', '', '', '', 'red', '', '', '', 'red', '', '', '', 'red', 'red', 'red', 'red', 'red'],
  ['', '', '', 'red', 'red', '', 'red', '', '', '', '', '', 'red', '', 'red', 'red', '', '', 'red', 'red'],
  ['red', '', '', '', 'red', 'red', 'red', '', '', '', '', '', 'red', 'red', 'red', '', '', '', '', 'red'],
  ['red', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'red'],
  ['red', '', '', '', 'red', 'red', 'red', '', '', '', '', '', 'red', 'red', 'red', '', '', '', '', 'red'],
  ['red', '', '', '', 'red', '', 'red', '', '', '', '', '', 'red', '', 'red', '', '', '', '', 'red'],
  ['red', '', '', 'red', 'red', '', 'red', 'red', '', '', '', 'red', 'red', '', 'red', 'red', '', '', 'red', 'red'],
  ['red', 'red', 'red', 'red', '', '', '', 'red', 'red', '', 'red', 'red', '', '', '', 'red', 'red', '', 'red', 'red'],
  ['red', 'red', 'red', '', '', '', '', '', 'red', 'red', 'red', '', '', '', '', '', 'red', '', 'red', 'red'],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red'],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
  ['red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'end']

]
export const cross = [
  ['start', 'red', '', '', '', '', '', '', 'red', 'red', 'red', 'red', '', '', '', '', '', '', '', ''],
  ['', 'red', '', '', '', '', '', 'red', 'red', 'red', 'red', 'red', 'red', '', '', '', '', '', '', ''],
  ['', 'red', '', '', '', '', '', 'red', 'red', 'red', 'red', 'red', 'red', '', '', '', '', '', '', ''],
  ['', 'red', '', '', '', '', '', '', 'red', '', '', 'red', '', '', '', '', '', '', '', ''],
  ['', 'red', '', 'red', 'red', 'red', 'red', 'red', 'red', '', '', 'red', 'red', 'red', 'red', 'red', 'red', '', '', ''],
  ['', 'red', '', 'red', '', '', '', '', '', '', '', '', '', '', '', '', 'red', '', '', ''],
  ['', 'red', '', 'red', '', '', '', '', '', '', '', '', '', '', '', '', 'red', '', '', ''],
  ['', 'red', '', 'red', 'red', 'red', 'red', 'red', 'red', '', '', 'red', 'red', 'red', 'red', 'red', 'red', '', '', ''],
  ['', 'red', 'red', 'red', '', 'red', 'red', 'red', 'red', '', '', 'red', 'red', 'red', 'red', '', 'red', 'red', 'red', 'red'],
  ['', 'red', '', '', '', '', '', 'red', 'red', '', '', 'red', 'red', '', '', '', '', '', 'red', 'red'],
  ['', 'red', 'red', 'red', '', 'red', 'red', 'red', 'red', '', '', 'red', 'red', 'red', 'red', '', 'red', 'red', 'red', 'red'], 
  ['', 'red', '', 'red', '', 'red', '', '', 'red', '', '', 'red', '', '', 'red', '', 'red', '', '', ''],
  ['', 'red', '', 'red', '', 'red', '', '', 'red', '', '', 'red', '', '', 'red', '', 'red', '', 'red', ''],
  ['', 'red', '', 'red', '', 'red', '', '', 'red', '', '', 'red', '', '', 'red', '', 'red', '', 'red', ''],
  ['', 'red', '', 'red', '', 'red', '', '', 'red', '', '', 'red', '', '', 'red', '', 'red', '', 'red', ''],
  ['', 'red', '', 'red', '', 'red', '', '', 'red', '', '', 'red', '', '', 'red', '', 'red', '', 'red', ''],
  ['', 'red', '', 'red', '', 'red', '', '', 'red', '', '', 'red', '', '', 'red', '', 'red', '', 'red', ''],
  ['', 'red', '', 'red', '', 'red', '', 'red', 'red', '', '', 'red', 'red', '', 'red', '', 'red', '', 'red', ''],
  ['', 'red', 'red', 'red', '', 'red', 'red', 'red', 'red', '', '', 'red', 'red', 'red', 'red', '', 'red', '', 'red', ''],
  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'red', 'end']

]
